# Generated by Django 3.2.5 on 2021-07-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
