# Generated by Django 3.2.5 on 2021-07-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_task_updated_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Created_time',
            new_name='created_time',
        ),
    ]
