# Generated by Django 3.2.5 on 2021-07-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0003_rename_created_time_task_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_time',
        ),
    ]
