# Generated by Django 3.2.5 on 2021-07-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0004_remove_task_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated_time',
            new_name='createdTime',
        ),
        migrations.AddField(
            model_name='task',
            name='updatedTime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
