# Generated by Django 3.2.5 on 2021-07-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0005_auto_20210722_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='task_created_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
