# Generated by Django 3.2.5 on 2021-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='createdTime',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='updatedTime',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
