# Generated by Django 3.2.5 on 2021-07-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20210721_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderdetails',
            name='created_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reminderdetails',
            name='updated_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='created_time',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='updated_time',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
