# Generated by Django 3.2.5 on 2021-07-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20210721_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderdetails',
            name='reminderStatus',
            field=models.CharField(default='Yet to remind', max_length=20),
        ),
    ]
